/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentation;
import Repositories.*;
import java.util.ArrayList;
import java.util.List;
import java.util.function.Consumer;
import Main.Functions;
import java.awt.BorderLayout;
import java.io.*;
/**
 *
 * @author Joshu
 */
public class RecepiePrincipale extends javax.swing.JFrame {
    RecepieRepo recepieRepo = new RecepieRepo("src\\main\\java\\Main\\recipes.xml");
    PrintStream originalOut = System.out;
    ByteArrayOutputStream os;
    PrintStream ps;
    String output;
    /**
     * Creates new form RecepiePrincipale
     * @throws java.lang.Exception
     */
    public RecepiePrincipale() throws Exception{
        initComponents();
        
        ActionComboBox.addItem("listRecepieTitles");
        ActionComboBox.addItem("calculateTotalEggs");
        ActionComboBox.addItem("getRecepiesWithOliveOil");
        ActionComboBox.addItem("calculateEggsPerRecepie");
        ActionComboBox.addItem("getLowCalorieRecepies");
        ActionComboBox.addItem("getSugarInZuppaInglese");
        ActionComboBox.addItem("printFirstTwoStepsOfZuppaInglese");
        ActionComboBox.addItem("getComplexRecepies");
        ActionComboBox.addItem("getRecepiesWithoutButter");
        ActionComboBox.addItem("getRecepiesCommonWithZuppaInglese");
        ActionComboBox.addItem("printMostCaloricRecepie");
        ActionComboBox.addItem("getMostFrequentUnit");
        ActionComboBox.addItem("numberIngredientsPerRecipe");
        ActionComboBox.addItem("getRecepieWithMostFat");
        ActionComboBox.addItem("calculateMostUsedIngredient");
        ActionComboBox.addItem("printRecipesSortedByIngredientCount");
        ActionComboBox.addItem("printRecipesByIngredient");
        ActionComboBox.addItem("calculateStepDistribution");
        ActionComboBox.addItem("getEasiestRecipe");
        

//        System.out.println(ActionComboBox.getItemCount());
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ActionComboBox = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextArea = new javax.swing.JTextArea();
        jToggleButton1 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ActionComboBox.setMaximumRowCount(20);
        ActionComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActionComboBoxActionPerformed(evt);
            }
        });

        TextArea.setEditable(false);
        TextArea.setColumns(20);
        TextArea.setLineWrap(true);
        TextArea.setRows(5);
        TextArea.setFocusable(false);
        jScrollPane1.setViewportView(TextArea);

        jToggleButton1.setText("ToggleChart");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(jToggleButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButton1))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ActionComboBox, 0, 270, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ActionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ActionComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActionComboBoxActionPerformed
        
        switch (ActionComboBox.getSelectedIndex()) {
            case 0 -> {
                os = new ByteArrayOutputStream();
                ps = new PrintStream(os);
                System.setOut(ps);
                Functions.listRecepieTitles(recepieRepo);
                ps.flush();
                output = os.toString();
                TextArea.setText(output);
                System.setOut(originalOut);
            }
            case 1 -> TextArea.setText(String.valueOf(Functions.calculateTotalEggs(recepieRepo)));
            case 2 -> TextArea.setText(Functions.getRecepiesWithOliveOil(recepieRepo).toString());
            case 3 -> TextArea.setText(Functions.calculateEggsPerRecepie(recepieRepo).toString());
            case 4 -> TextArea.setText(Functions.getLowCalorieRecepies(recepieRepo).toString());
            case 5 -> TextArea.setText(Functions.getSugarInZuppaInglese(recepieRepo).toString());
            case 6 -> {
                os = new ByteArrayOutputStream();
                ps = new PrintStream(os);
                System.setOut(ps);
                Functions.printFirstTwoStepsOfZuppaInglese(recepieRepo);
                ps.flush();
                output = os.toString();
                TextArea.setText(output);
                System.setOut(originalOut);
            }
            case 7 -> TextArea.setText(Functions.getComplexRecepies(recepieRepo).toString());
            case 8 -> TextArea.setText(Functions.getRecepiesWithoutButter(recepieRepo).toString());
            case 9 -> TextArea.setText(Functions.getRecepiesCommonWithZuppaInglese(recepieRepo).toString());
            case 10 -> {
                os = new ByteArrayOutputStream();
                ps = new PrintStream(os);
                System.setOut(ps);
                Functions.printMostCaloricRecepie(recepieRepo);
                ps.flush();
                output = os.toString();
                TextArea.setText(output);
                System.setOut(originalOut);
            }
            case 11 -> TextArea.setText(Functions.getMostFrequentUnit(recepieRepo).toString());
            case 12 -> TextArea.setText(Functions.numberIngredientsPerRecipe(recepieRepo).toString());
            case 13 -> TextArea.setText(Functions.getRecepieWithMostFat(recepieRepo).toString());
            case 14 -> TextArea.setText(Functions.calculateMostUsedIngredient(recepieRepo));
            case 15 -> {
                os = new ByteArrayOutputStream();
                ps = new PrintStream(os);
                System.setOut(ps);
                Functions.printRecipesSortedByIngredientCount(recepieRepo);
                ps.flush();
                output = os.toString();
                TextArea.setText(output);
                System.setOut(originalOut);
            }
            case 16 -> {
                os = new ByteArrayOutputStream();
                ps = new PrintStream(os);
                System.setOut(ps);
                Functions.printRecipesByIngredient(recepieRepo);
                ps.flush();
                output = os.toString();
                TextArea.setText(output);
                System.setOut(originalOut);
            }
            case 17 -> TextArea.setText(Functions.calculateStepDistribution(recepieRepo).toString());
            case 18 -> TextArea.setText(Functions.getEasiestRecipe(recepieRepo));
            default -> throw new AssertionError();
        }
    }//GEN-LAST:event_ActionComboBoxActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        TextArea.setVisible(!jToggleButton1.getModel().isSelected());
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecepiePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecepiePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecepiePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecepiePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try{
                    new RecepiePrincipale().setVisible(true);
                }catch (Exception e){
                    System.out.println(e);
                }
                    
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ActionComboBox;
    private javax.swing.JTextArea TextArea;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
