/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentation;

import Main.Functions;
import Repositories.RecepieRepo;
import java.io.ByteArrayOutputStream;
import java.io.PrintStream;
import java.util.List;
import java.util.Map;

/**
 *
 * @author Joshua Pugh & Anya
 */
public class RecepiePrincipale extends javax.swing.JFrame {
    RecepieRepo recepieRepo = new RecepieRepo("src/main/java/Main/recipes.xml");
    PrintStream originalOut = System.out;
    ByteArrayOutputStream os;
    PrintStream ps;
    String output;
    /**
     * Creates new form RecepiePrincipale
     */
    public RecepiePrincipale() throws Exception {
        initComponents();
        
        ActionComboBox.addItem("listRecepieTitles");
        ActionComboBox.addItem("calculateTotalEggs");
        ActionComboBox.addItem("getRecepiesWithOliveOil");
        ActionComboBox.addItem("calculateEggsPerRecepie");
        ActionComboBox.addItem("getLowCalorieRecepies");
        ActionComboBox.addItem("getSugarInZuppaInglese");
        ActionComboBox.addItem("printFirstTwoStepsOfZuppaInglese");
        ActionComboBox.addItem("getComplexRecepies");
        ActionComboBox.addItem("getRecepiesWithoutButter");
        ActionComboBox.addItem("getRecepiesCommonWithZuppaInglese");
        ActionComboBox.addItem("printMostCaloricRecepie");
        ActionComboBox.addItem("getMostFrequentUnit");
        ActionComboBox.addItem("numberIngredientsPerRecipe");
        ActionComboBox.addItem("getRecepieWithMostFat");
        ActionComboBox.addItem("calculateMostUsedIngredient");
        ActionComboBox.addItem("printRecipesSortedByIngredientCount");
        ActionComboBox.addItem("printRecipesByIngredient");
        ActionComboBox.addItem("calculateStepDistribution");
        ActionComboBox.addItem("getEasiestRecipe");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jPanel = new javax.swing.JPanel();
        ActionComboBox = new javax.swing.JComboBox<>();
        jToggleButton2 = new javax.swing.JToggleButton();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextArea = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        pieChartPanel1 = new Presentation.PieChartPanel();

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ActionComboBox.setMaximumRowCount(19);
        ActionComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ActionComboBoxActionPerformed(evt);
            }
        });

        jToggleButton2.setText("Toggle Text/Graph");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        TextArea.setEditable(false);
        TextArea.setColumns(20);
        TextArea.setLineWrap(true);
        TextArea.setRows(5);
        TextArea.setFocusable(false);
        jScrollPane1.setViewportView(TextArea);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pieChartPanel1Layout = new javax.swing.GroupLayout(pieChartPanel1);
        pieChartPanel1.setLayout(pieChartPanel1Layout);
        pieChartPanel1Layout.setHorizontalGroup(
            pieChartPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 335, Short.MAX_VALUE)
        );
        pieChartPanel1Layout.setVerticalGroup(
            pieChartPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 292, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pieChartPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pieChartPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLayeredPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelLayout = new javax.swing.GroupLayout(jPanel);
        jPanel.setLayout(jPanelLayout);
        jPanelLayout.setHorizontalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ActionComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLayeredPane1)
            .addComponent(jToggleButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelLayout.setVerticalGroup(
            jPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelLayout.createSequentialGroup()
                .addComponent(ActionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButton2))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ActionComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ActionComboBoxActionPerformed
        pieChartPanel1.setData(new int[0]);
        pieChartPanel1.setLabels(new String[0]);
        switch (ActionComboBox.getSelectedIndex()) {
            case 0 -> {
                os = new ByteArrayOutputStream();
                ps = new PrintStream(os);
                System.setOut(ps);
                Functions.listRecepieTitles(recepieRepo);
                ps.flush();
                output = os.toString();
                TextArea.setText(output);
                System.setOut(originalOut);
            }
            case 1 -> TextArea.setText(String.valueOf(Functions.calculateTotalEggs(recepieRepo)));
            case 2 -> TextArea.setText(Functions.getRecepiesWithOliveOil(recepieRepo).toString());
            case 3 ->{
                Map<String,Double> res = Functions.calculateEggsPerRecepie(recepieRepo);
                TextArea.setText(res.toString());
                int[] integerList = res.values().stream()
                                        .mapToInt(Double::intValue)
                                        .toArray();
                String[] keysArray = res.keySet().toArray(new String[0]);
                
                pieChartPanel1.setData(integerList);
                pieChartPanel1.setLabels(keysArray);
            }
            case 4 -> TextArea.setText(Functions.getLowCalorieRecepies(recepieRepo).toString());
            case 5 -> TextArea.setText(Functions.getSugarInZuppaInglese(recepieRepo).toString());
            case 6 -> {
                os = new ByteArrayOutputStream();
                ps = new PrintStream(os);
                System.setOut(ps);
                Functions.printFirstTwoStepsOfZuppaInglese(recepieRepo);
                ps.flush();
                output = os.toString();
                TextArea.setText(output);
                System.setOut(originalOut);
            }
            case 7 -> TextArea.setText(Functions.getComplexRecepies(recepieRepo).toString());
            case 8 -> TextArea.setText(Functions.getRecepiesWithoutButter(recepieRepo).toString());
            case 9 -> TextArea.setText(Functions.getRecepiesCommonWithZuppaInglese(recepieRepo).toString());
            case 10 -> {
                os = new ByteArrayOutputStream();
                ps = new PrintStream(os);
                System.setOut(ps);
                Functions.printMostCaloricRecepie(recepieRepo);
                ps.flush();
                output = os.toString();
                TextArea.setText(output);
                System.setOut(originalOut);
            }
            case 11 -> TextArea.setText(Functions.getMostFrequentUnit(recepieRepo).toString());
            case 12 -> {
                Map<String,String> res = Functions.numberIngredientsPerRecipe(recepieRepo);
                TextArea.setText(res.toString());
                int[] integerList = res.values().stream()
                                        .mapToInt(Integer::parseInt)
                                        .toArray();
                
                String[] keysArray = res.keySet().toArray(new String[0]);
                
                pieChartPanel1.setData(integerList);
                pieChartPanel1.setLabels(keysArray);
            }
            case 13 -> TextArea.setText(Functions.getRecepieWithMostFat(recepieRepo).toString());
            case 14 -> TextArea.setText(Functions.calculateMostUsedIngredient(recepieRepo));
            case 15 -> {
                os = new ByteArrayOutputStream();
                ps = new PrintStream(os);
                System.setOut(ps);
                Functions.printRecipesSortedByIngredientCount(recepieRepo);
                ps.flush();
                output = os.toString();
                TextArea.setText(output);
                System.setOut(originalOut);
            }
            case 16 -> {
                os = new ByteArrayOutputStream();
                ps = new PrintStream(os);
                System.setOut(ps);
                Functions.printRecipesByIngredient(recepieRepo);
                ps.flush();
                output = os.toString();
                TextArea.setText(output);
                System.setOut(originalOut);
            }
            case 17 -> {
                Map<Integer, List<String>> res = Functions.calculateStepDistribution(recepieRepo);
                int totalCount = res.values().stream()
                                    .mapToInt(List::size)
                                    .sum();
                
                int[] intRes = new int[totalCount];
                String[] strRes = new String[totalCount];
                int cmt = 0;
                for (Integer key : res.keySet()) {
                    for (String s : res.get(key)) {
                        intRes[cmt] = key;
                        strRes[cmt] = s;
                        cmt ++;
                    }
                }
                
                TextArea.setText(res.toString());
                
                pieChartPanel1.setData(intRes);
                pieChartPanel1.setLabels(strRes);
            }
            case 18 -> TextArea.setText(Functions.getEasiestRecipe(recepieRepo));
            default -> throw new AssertionError();
        }
        getContentPane().repaint();
    }//GEN-LAST:event_ActionComboBoxActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        jPanel1.setVisible(!jToggleButton2.getModel().isSelected());
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecepiePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecepiePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecepiePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecepiePrincipale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 try{
                    new RecepiePrincipale().setVisible(true);
                }catch (Exception e){
                    System.out.println(e);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ActionComboBox;
    private javax.swing.JTextArea TextArea;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JToggleButton jToggleButton2;
    private Presentation.PieChartPanel pieChartPanel1;
    // End of variables declaration//GEN-END:variables
}
